server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Carlos3108/erudio-config-service
          default-label: main
          search-paths:
          - 'greeting-service*'